<%
  provisioner = ENV['KITCHEN_PROVISIONER'] || 'chef_zero'
  omnibus_version = ENV['KITCHEN_OMNIBUS_VER'] || 'true'
  driver = ENV['KITCHEN_DRIVER'] || 'vagrant'
%>

---
driver_plugin: <%= driver %>

<% if driver == 'digitalocean' %>
driver_config:
  digitalocean_client_id: <%= ENV['DIGITALOCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITALOCEAN_API_KEY'] %>
  region_id: <%= ENV['DIGITALOCEAN_REGION_ID'] || '1' %>
  ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
  ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY'] %>
  flavor_id: 64
<% else %>
driver_config:
  customize:
    # Zenoss doesn't do well with the default 256MB
    # Avoid OSError: [Errno 12] Cannot allocate memory when starting Zenoss
    # TODO - Core 3 has far less requirements. Figure out if its possible
    # to only have the really high memory amount on Core4 suite instances
    memory: 3072
  require_chef_omnibus: true
<% end %>

provisioner:
  name: <%= provisioner %>
  require_chef_omnibus: <%= omnibus_version %>

platforms:
- name: ubuntu-12
  driver_config:
  <% if driver == 'vagrant' %>
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  <% elsif driver == 'digitalocean' %>
    image_id: 284203
  <% elsif driver == 'docker' %>
    image: ubuntu:12.04
  <% end %>

- name: ubuntu-10
  driver_config:
  <% if driver == 'vagrant' %>
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  <% elsif driver == 'digitalocean' %>
    image_id: 14097
  <% elsif driver == 'docker' %>
    image: ubuntu:10.04
  <% end %>

- name: centos-6
  driver_config:
  <% if driver == 'vagrant' %>
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  <% elsif driver == 'digitalocean' %>
    image_id: 562354
  <% elsif driver == 'docker' %>
    image: centos:6.4
  <% end %>

- name: centos-5
  driver_config:
  <% if driver == 'vagrant' %>
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
  <% elsif driver == 'digitalocean' %>
    image_id: 1601
  <% elsif driver == 'docker' %>
    # TODO put a real value here. I'm not sure of a good Centos 5 docker image, but if you omit
    # a value here, kitchen will bomb
    image: centos:5.9
  <% end %>

suites:
- name: zenoss_core3
  run_list: 
  - recipe[minitest-handler]
  - recipe[zenoss::server]
  attributes:
    zenoss:
      server:
        version: "3.2.1-0"
      client:
        server: "localhost"
        port: 8080
    java:
      oracle:
        accept_oracle_download_terms: true
- name: zenoss_core4
  run_list: 
  - recipe[minitest-handler]
  - recipe[zenoss::server]
  attributes:
    zenoss:
      server:
        version: "4.2.5"
      client:
        server: "localhost"
        port: 8080
    java:
      oracle:
        accept_oracle_download_terms: true
    minitest:
      filter: /zenoss/
